# Generated by Django 5.1.2 on 2024-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('C_Image', models.ImageField(blank=True, null=True, upload_to='category_img')),
                ('C_Desc', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
