# Generated by Django 5.1.2 on 2024-10-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_email', models.CharField(blank=True, max_length=100, null=True)),
                ('s_mob', models.CharField(blank=True, max_length=100, null=True)),
                ('s_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('s_newpass', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
