# Generated by Django 5.1.2 on 2024-10-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signup_db',
        ),
    ]
