# Generated by Django 4.0.3 on 2024-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_orderdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='totalp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
