# Generated by Django 4.0.3 on 2024-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_cartdb_cart_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='cart_img',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_Images'),
        ),
    ]
