# Generated by Django 5.1.2 on 2024-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_cartdb_cart_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='tprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
