# Generated by Django 5.1.2 on 2024-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_cartdb_tprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='totalp',
            new_name='tprice',
        ),
    ]
